### ISSUE TITLE
CoinInfo 구현

### ISSUE THREAD

**Issue by binkoni** [cau-team-project/gazua#3]
사실상 데이터를 담는 역할정도만 하면 된다

**Comment by mskim9967** [comment]
완료
getter setter 쓰는게 좋을지?
자료형은 double? long double? 무엇을 쓰는게 바람직한가?

**Comment by binkoni** [comment]
@mskim9967 
> getter setter 쓰는게 좋을지?

이 부분은 아직 더 윤곽이 잡혀봐야 알 것 같은데 만약에 데이터 담는 역할 이외에 따로 추가할 만한 메서드가 없으면 class 대신 struct 키워드를 사용하는 것도 좋을 것 같습니다.
> double로 수량을 저장하는게 바람직한가?

거래량은 좀 애매하긴 한데 서버에서 그렇게 돌려주니 일단은 안바꾸셔도 될 것 같고
매수/매도 최소 최대 수량은 코인 한개 가격이 너무 비싸져서(예를 들면 1비트코인에 몇백만원) 실제로 소수점 단위로 거래하기때문에 double이 맞습니다..
